### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Ordosbxy** [Pigcasso/AppChooser#1]
你好， 能否上传一下gradle中自定义的变量文件，编译报错了，找不见
    compile deps.support
    compile deps.rxjava
    compile deps.rxandroid
    compile deps.sqlbrite
    compile deps.supportrecyclerview
    compile deps.zhybaservadapter
    compile deps.eventbus
谢谢！

**Comment by JulianAndroid** [comment]
我把公共的gradle配置信息都写在这里了：https://github.com/JulianAndroid/gradle-common-plugin/blob/master/common_config.gradle
你可以在项目根目录的build.gradle中看到：
`apply from: 'https://raw.githubusercontent.com/JulianAndroid/gradle-common-plugin/master/android-common-plugin.gradle'`

**Comment by Ordosbxy** [comment]
Thank you, 编译通过跑起来。请问你公司的企业网盘产品叫啥？ 我公司用的是亿方云， 个人也用过坚果云。

**Comment by JulianAndroid** [comment]
哈哈，我是坚果云的。
