### ISSUE TITLE
这个是ActionView的自定义，把ActionSend的也自定义一下吧

### ISSUE THREAD

**Issue by hegelsu** [Pigcasso/AppChooser#2]
View的还是可以自己处理一下的，Send的Choose简直要完全重写了

**Comment by JulianAndroid** [comment]
哥们，你遇到什么关于ACTION_SEND的问题了，还是纯粹想自定义ACTION_SENED?

**Comment by hegelsu** [comment]
我遇到的问题是：App做了网盘的功能，所以有设置了*.*，但App又有分享的功能，在分享的时候用的也是*.*，这样弹出的分享菜单就有自己了，所以想把自己去掉，但发现Send的不像view那样可以设置ExtraInitialIntents来自定义，好麻烦

另外你的那个弹出的界面能再美化一下么，最好颜色能自定义啥的，我准备引用这个库了。

最好感谢作者，这个库不错。

**Comment by JulianAndroid** [comment]
明白你的意思了。我先记下，忙完手头的活，可以考虑添加**自定义主题**和**ACTION_SEND**。

**Comment by hegelsu** [comment]
好的，静待佳音

**Comment by hegelsu** [comment]
天天来看有没有更新，坐等Send功能。。。

**Comment by JulianAndroid** [comment]
别这样，我也是上班领工资的。写到现在这个程度，我就花了一个多月。

**Comment by hegelsu** [comment]
没事啦，我只是看到你更新了，过来冒个泡

**Comment by JulianAndroid** [comment]
你现在使用的是 ACTION_SEND 的那种用法？是这种吗：
```java
Intent sendIntent = new Intent();
sendIntent.setAction(Intent.ACTION_SEND);
sendIntent.putExtra(Intent.EXTRA_TEXT, "This is my text to send.");
sendIntent.setType("text/plain");
startActivity(sendIntent);
```

**Comment by hegelsu** [comment]
是的

**Comment by hegelsu** [comment]
持续关注中。。。

**Comment by JulianAndroid** [comment]
哈哈，如果周六周日再努力一天，下周一估计就能发布咯~~

**Comment by hegelsu** [comment]
好的，辛苦了

**Comment by JulianAndroid** [comment]
你好，新版本我已经提交上去了。导入项目：`compile 'io.julian:appchooser:2.0.0'`。
如果有问题随时跟我联系哈。

**Comment by hegelsu** [comment]
好的，我抽空看下。

**Comment by hegelsu** [comment]
有个建议，如果可以的话，最好还是一个库。另外Demo也可以有空更新下

**Comment by JulianAndroid** [comment]
“最好还是一个库”是什么意思？本来就是一个库呀，不过使用方法变了，不能跟1.x.x的版本兼容。

**Comment by hegelsu** [comment]
就是把common和mvp用到的合到appchooser里

**Comment by JulianAndroid** [comment]
我考虑一下哈，谢谢提醒
