### ISSUE TITLE
加入依赖编译通过好艰难

### ISSUE THREAD

**Issue by FrankLove** [Pigcasso/AppChooser#7]
1、直接引入依赖编译报错
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.1.0-alpha05] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:20:5-196:19 to override.
2、根据提示加入tools:replace="android:appComponentFactory" 报错
 Manifest merger failed with multiple errors, see logs

**Comment by Pigcasso** [comment]
应该是由于你的项目中android.support库跟androidx库发生冲突导致的。
